# Generated by Django 6.0 on 2026-01-01 12:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='IllnessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('respiratory', 'Respiratory (Lungs, Breathing)'), ('cardiovascular', 'Heart & Circulation'), ('gastrointestinal', 'Digestive System'), ('neurological', 'Brain & Nerves'), ('musculoskeletal', 'Muscles & Bones'), ('skin', 'Skin Conditions'), ('infectious', 'Infectious Diseases'), ('endocrine', 'Hormones & Metabolism'), ('mental_health', 'Mental Health'), ('other', 'Other')], max_length=100)),
                ('description', models.TextField(help_text='Brief explanation of what this illness is')),
                ('primary_symptoms', models.TextField(help_text='Main symptoms people experience (comma-separated)')),
                ('severity', models.CharField(choices=[('self_care', 'Usually Self-Care'), ('doctor', 'See a Doctor'), ('urgent', 'Urgent Care Needed'), ('emergency', 'Medical Emergency')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, null=True)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('known_conditions', models.TextField(blank=True, help_text='Known medical conditions', null=True)),
                ('allergies', models.TextField(blank=True, help_text='Known allergies', null=True)),
                ('blood_pressure', models.CharField(blank=True, help_text='Format: 120/80', max_length=20, null=True)),
                ('last_checkup_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(help_text='Describe your symptom', max_length=200)),
                ('body_part', models.CharField(choices=[('head', 'Head (Headache, Dizziness)'), ('eyes', 'Eyes (Vision, Pain)'), ('ears', 'Ears (Hearing, Pain)'), ('nose', 'Nose (Congestion, Bleeding)'), ('mouth', 'Mouth/Throat (Sore throat, Swallowing)'), ('chest', 'Chest (Pain, Breathing)'), ('abdomen', 'Abdomen (Stomach pain, Digestion)'), ('back', 'Back (Pain, Stiffness)'), ('arms', 'Arms/Hands (Pain, Numbness)'), ('legs', 'Legs/Feet (Pain, Swelling)'), ('skin', 'Skin (Rash, Itching)'), ('urinary', 'Urinary (Pain, Frequency)'), ('general', 'General (Fever, Fatigue)')], max_length=50)),
                ('severity', models.IntegerField(choices=[(1, 'Mild'), (2, 'Moderate'), (3, 'Severe')], default=2)),
                ('duration', models.CharField(choices=[('hours', 'Hours (Less than 24 hours)'), ('days', 'Days (1-7 days)'), ('weeks', 'Weeks (1-4 weeks)'), ('months', 'Months (More than 1 month)')], default='days', max_length=20)),
                ('started_when', models.DateTimeField(help_text='When did this symptom start?')),
                ('description', models.TextField(blank=True, help_text='Describe in your own words', null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('possible_illnesses', models.JSONField(default=list, help_text='List of possible illnesses with match scores')),
                ('confidence_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('urgency_level', models.CharField(choices=[('self_monitor', 'Monitor at Home'), ('schedule_appointment', 'Schedule Doctor Visit'), ('urgent_care', 'Consider Urgent Care'), ('emergency', 'Seek Emergency Care')], max_length=50)),
                ('symptom_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='guidence.symptomlog')),
            ],
        ),
        migrations.CreateModel(
            name='SymptomPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(help_text='e.g., Morning headaches, After-meal stomach pain', max_length=200)),
                ('description', models.TextField()),
                ('impact_level', models.CharField(choices=[('low', 'Low Impact'), ('moderate', 'Moderate Impact'), ('high', 'High Impact')], max_length=50)),
                ('detected_date', models.DateTimeField(auto_now_add=True)),
                ('last_occurrence', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_patterns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
